GROQ_API_KEY = "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"
REDIS_URL = "redis://localhost:6379/0"

[[users]]
username = "houssem"
password_hash = "$2b$12$yLbDDV.uepG7VExS1lz61.8M3dR4/MZaETWuaj27bRbiCft.RpEi6"
