GROQ_API_KEY = "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"
REDIS_URL = "redis://localhost:6379/0"
DATABASE_URL = "postgresql://postgres.ohzdozxgqxmpamosghec:houssem.ai55@aws-0-eu-west-3.pooler.supabase.com:5432/postgres"
